# Generated by Django 4.0.2 on 2022-06-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Уникалное название товара')),
                ('title', models.CharField(max_length=100, verbose_name='Название товара')),
                ('desc', models.TextField(max_length=250, verbose_name='Описание товара')),
                ('price', models.IntegerField(default=1000, verbose_name='Цена товара')),
                ('image', models.ImageField(default='default.jpg', upload_to='horizon_images', verbose_name='Изображение товара')),
            ],
        ),
    ]
