# Generated by Django 4.0.2 on 2022-06-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.png', upload_to='horizon_images', verbose_name='Изображение товара'),
        ),
    ]
